outputDoublets_metamouse.saveAll_doublets = [outputDoublets_E22.saveAll_doublets...
    outputDoublets_E39.saveAll_doublets...
    outputDoublets_E43.saveAll_doublets...
    outputDoublets_E44.saveAll_doublets...
    outputDoublets_E47.saveAll_doublets...
    outputDoublets_E48.saveAll_doublets...
    outputDoublets_E65.saveAll_doublets...
    ];

outputDoublets_metamouse.saveAll_doublets_Sig = [outputDoublets_E22.saveAll_doublets_Sig...
    outputDoublets_E39.saveAll_doublets_Sig...
    outputDoublets_E43.saveAll_doublets_Sig...
    outputDoublets_E44.saveAll_doublets_Sig...
    outputDoublets_E47.saveAll_doublets_Sig...
    outputDoublets_E48.saveAll_doublets_Sig...
    outputDoublets_E65.saveAll_doublets_Sig...
    ];

outputDoublets_metamouse.saveAll_doublets_NotSig = [outputDoublets_E22.saveAll_doublets_NotSig...
    outputDoublets_E39.saveAll_doublets_NotSig...
    outputDoublets_E43.saveAll_doublets_NotSig...
    outputDoublets_E44.saveAll_doublets_NotSig...
    outputDoublets_E47.saveAll_doublets_NotSig...
    outputDoublets_E48.saveAll_doublets_NotSig...
    outputDoublets_E65.saveAll_doublets_NotSig...
    ];

outputDoublets_metamouse.saveAll_doublets_Sig_Left = [outputDoublets_E22.saveAll_doublets_Sig_Left...
    outputDoublets_E39.saveAll_doublets_Sig_Left...
    outputDoublets_E43.saveAll_doublets_Sig_Left...
    outputDoublets_E44.saveAll_doublets_Sig_Left...
    outputDoublets_E47.saveAll_doublets_Sig_Left...
    outputDoublets_E48.saveAll_doublets_Sig_Left...
    outputDoublets_E65.saveAll_doublets_Sig_Left...
    ];

outputDoublets_metamouse.saveAll_doublets_Sig_Right = [outputDoublets_E22.saveAll_doublets_Sig_Right...
    outputDoublets_E39.saveAll_doublets_Sig_Right...
    outputDoublets_E43.saveAll_doublets_Sig_Right...
    outputDoublets_E44.saveAll_doublets_Sig_Right...
    outputDoublets_E47.saveAll_doublets_Sig_Right...
    outputDoublets_E48.saveAll_doublets_Sig_Right...
    outputDoublets_E65.saveAll_doublets_Sig_Right...
    ];