

outputTriplets_metamouse.saveAll_triplets = [outputTriplets_E22.saveAll_triplets;...
    outputTriplets_E39.saveAll_triplets;...
    outputTriplets_E43.saveAll_triplets;...
    outputTriplets_E44.saveAll_triplets;...
    outputTriplets_E47.saveAll_triplets;...
    outputTriplets_E48.saveAll_triplets;...
    outputTriplets_E65.saveAll_triplets...
    ];

outputTriplets_metamouse.saveAll_triplets_Sig = [outputTriplets_E22.saveAll_triplets_Sig;...
    outputTriplets_E39.saveAll_triplets_Sig;...
    outputTriplets_E43.saveAll_triplets_Sig;...
    outputTriplets_E44.saveAll_triplets_Sig;...
    outputTriplets_E47.saveAll_triplets_Sig;...
    outputTriplets_E48.saveAll_triplets_Sig;...
    outputTriplets_E65.saveAll_triplets_Sig...
    ];

outputTriplets_metamouse.saveAll_triplets_NotSig = [outputTriplets_E22.saveAll_triplets_NotSig;...
    outputTriplets_E39.saveAll_triplets_NotSig;...
    outputTriplets_E43.saveAll_triplets_NotSig;...
    outputTriplets_E44.saveAll_triplets_NotSig;...
    outputTriplets_E47.saveAll_triplets_NotSig;...
    outputTriplets_E48.saveAll_triplets_NotSig;...
    outputTriplets_E65.saveAll_triplets_NotSig...
    ];

outputTriplets_metamouse.saveAll_triplets_great4 = [outputTriplets_E22.saveAll_triplets_great4;...
    outputTriplets_E39.saveAll_triplets_great4;...
    outputTriplets_E43.saveAll_triplets_great4;...
    outputTriplets_E44.saveAll_triplets_great4;...
    outputTriplets_E47.saveAll_triplets_great4;...
    outputTriplets_E48.saveAll_triplets_great4;...
    outputTriplets_E65.saveAll_triplets_great4...
    ];

outputTriplets_metamouse.saveAll_triplets_Sig_Left = [outputTriplets_E22.saveAll_triplets_Sig_Left;...
    outputTriplets_E39.saveAll_triplets_Sig_Left;...
    outputTriplets_E43.saveAll_triplets_Sig_Left;...
    outputTriplets_E44.saveAll_triplets_Sig_Left;...
    outputTriplets_E47.saveAll_triplets_Sig_Left;...
    outputTriplets_E48.saveAll_triplets_Sig_Left;...
    outputTriplets_E65.saveAll_triplets_Sig_Left...
    ];

outputTriplets_metamouse.saveAll_triplets_Sig_Right = [outputTriplets_E22.saveAll_triplets_Sig_Right;...
    outputTriplets_E39.saveAll_triplets_Sig_Right;...
    outputTriplets_E43.saveAll_triplets_Sig_Right;...
    outputTriplets_E44.saveAll_triplets_Sig_Right;...
    outputTriplets_E47.saveAll_triplets_Sig_Right;...
    outputTriplets_E48.saveAll_triplets_Sig_Right;...
    outputTriplets_E65.saveAll_triplets_Sig_Right...
    ];
